### ISSUE TITLE
Is the significant performance difference between timezone{16,21} files to be expected?

### ISSUE THREAD

**Issue by jpmens** [BertoldVdb/ZoneDetect#43]
Thank you very much for doing this! We're thinking about adding the library as a feature to our OwnTracks Recorder in order to provide timezone information of stored locations when using the API.

I note there is quite a performance penalty in using the `timezone21` database files versus the `timezone16` ones.

In order to test, I created a file with 102,681 lines containing an epoch timestamp, latitude, and longitude:

```console
$ head -1 loc.list
1557843001 45.43093872070312 -75.70665203324675
```

As small test program based on your `demo.c` reads the file and looks up time zones:

```c
int main(int argc, char *argv[])
{
	long tst;
	float lat, lon;

// #define DB "out_v1/timezone21.bin"
#define DB "out/timezone16.bin"
	ZDSetErrorHandler(onError);
	ZoneDetect *const cd = ZDOpenDatabase(DB);
	if(!cd) return 2;

	while (scanf("%ld %f %f", &tst, &lat, &lon) != EOF) {

		char *z = ZDHelperSimpleLookupString(cd, lat, lon);

		printf("%ld %8.5f %8.5f %s\n", tst, lat, lon, z);
		ZDHelperSimpleLookupStringFree(z);
	}
	ZDCloseDatabase(cd);
	return 0;
}
```

Using `out/timezone16.bin`, the program runs in 

```console
$ wc -l loc.list
  102681 loc.list

$ time ./jp < loc.list > /dev/null
real	1m13.643s
user	1m13.144s
sys	0m0.255s
```

Recompiling and using `out/timezone21.bin`, the program runs in

```console
$ time ./jp < loc.list > /dev/null
real	6m33.025s
user	6m30.769s
sys	0m0.686s
```

The files I currently have (last version from your `db.zip) are

```console
$ du -sh out/timezone16.bin out/timezone21.bin
3.1M	out/timezone16.bin
 11M	out/timezone21.bin
```

Is that quite significant difference in runtime to be expected?

**Comment by BertoldVdb** [comment]
Hello,

Yes, it is to be expected. The library wasn't really written with efficiency in mind, as it was used on an embedded device that only has to do a few lookups a day. The point-in-polygon calculation is linear in the number of points, and you have significantly more in the timezone21 file.

Also, the way to find which zones to consider is quite naive and inefficient, which results in large countries such as Russia frequently being evaluated.

It seems in your testcase the timezone21 lookups take around 4ms per query. Could it be an option to perform the queries while logging the points instead of calculating them all when serving the log? To not bulk up the log, you could save the numeric TimezoneId and later convert it into a name.

If this is not possible, is there a minimum performance level you need?

Sincerely,
Bertold

**Comment by jpmens** [comment]
This bulk test was just to get a feeling for what the library is capable of doing; I've no particular requirement for performance, as most of our users have relative low volume of data, and a few dozen ms per lookup won't hurt much.

Thank you for your response. I should have paid more attention to this sentence:

> The files in the folder out_v1/ use a newer format and use less space to encode the same information.

If the data quality is identical, I'll use the `out/timezone16.bin` file; the 2MB savings in `out_v1/timezone16.bin` aren't really worth it for this application.

**Comment by BertoldVdb** [comment]
Hello,

The number indicates the resolution. The 21 file has a higher resolution for storing the borders, but it is larger. The 16 file has a longitude resolution of 0.0055 degrees (~0.5km) and the 21 file has 0.00017 degrees (~20m).

I will add this information to the readme. The out_v1 files are smaller than the out_v0 files as they contain deduplicated edges.

Sincerely,
Bertold
