### ISSUE TITLE
I found some different time zone id 

### ISSUE THREAD

**Issue by iknow34languages** [BertoldVdb/ZoneDetect#6]
@BertoldVdb 

i did a test that i input many positions coming from edges to java and your project

and i got the results:
https://github.com/iknow34languages/Problems/tree/questions/question_2

and found there is 71 different results.

you can compare it;

i don't know how what happened.

:(

**Comment by BertoldVdb** [comment]
Hello,

Case 1: Sometimes the C code reports multiple positions together with "Target point is on border". This means that the code cannot know with the position you provided since it is so close to the border between zones that the database quantization does not allow telling them apart. A lot of borders in Africa have an integer longitude and/or latitude component, for example the border between Sudan and Chad is defined to be at 24E. This causes your testcase to hit this issue quite often.

It seems the Java library simply gives you one of the timezones in this case. If this is good enough, you can do the same, just take the first result from the array.

Case 2:
The Java API sometimes does not find some coordinates. It seems my result is correct. Eg: 78.0 -60.0 is in Greenland, -46.0 -71.0 is in Argentina.

Case 3:
Sometimes the result is a different zone. This is because the point is really close to the border between the zones. I think the Java library uses a smaller database with less precision, this is also the cause of 2.

I recommend not testing with integer latitude and longitude, this puts you close to a large amount of zone boundaries. Put a random fractional part.

Sincerely,
Bertold

**Comment by BertoldVdb** [comment]
PS: Is it critical for you to match the results of this Java application exactly? If yes, I could try to make a database file made from their source data with their quantization. This should then give the same results.

**Comment by iknow34languages** [comment]
@BertoldVdb 
i saw that their project use the very high accuracy map data; and i check the map data is almost the same on the open street map.

while your project change the lat long data struct to another way to reduce memory cost.

so i don't know if the difference is coming from your origin map data or data change algorithm;

**Comment by BertoldVdb** [comment]
Hello,

Yes, indeed. They use the same underlying data is me. I also don't see any quantization in the Java program (and its memory usage and database size seem to agree with that) so I don't see where the differences come from.

Maybe we should also open an issue in the Java project? I am not convinced the error is in this repository.

For example: 46S 70W
Google maps: https://www.google.be/maps/place/46%C2%B000'00.0%22S+70%C2%B000'00.0%22W/@-46.0226504,-70.1075851,12.5z/data=!4m5!3m4!1s0x0:0x0!8m2!3d-46!4d-70
My code says: America/Argentina/Rio_Gallegos
The java code says: Not Found

But it seems on Google Maps that it is indeed in Argentina, and in the Santa Cruz province, so the result seems correct. Again you are testing with a point very close to the border though... However, should a rounding error give you the result on the other side of the border the result should be America/Argentina/Catamarca and not "Not Found"

Sincerely,
Bertold Van den Bergh

**Comment by iknow34languages** [comment]
@BertoldVdb 

give 45S 70W
it returns : America/Argentina/Catamarca
:)

**Comment by BertoldVdb** [comment]
@evansiroky Ok, I will update the bin files when you release a new version.

**Comment by BertoldVdb** [comment]
Updated
